const actionTypes = Object.freeze({
     // Home
     MODAL : "CHANGE_STATUS_MODAL",
     CHANGE_BACKGROUND : "CHANGE_BACKGROUND",
     CHANGE_STATUS_MENU: "CHANGE_STATUS_MENU",
     GET_DETAIL: "GET_DETAIL",
     HANDEL_CLICK_MODAL: "HANDEL_CLICK_MODAL",
     HANDEL_CLICK_SETTING: "HANDEL_CLICK_SETTING",


     // Wallet
     CONNECT_WALLET: "CONNECT_WALLET",
     CONNECT_METAMASK: "CONNECT_METAMASK",
     RE_RENDER_METAMASK: "RE_RENDER_METAMASK",
     CONNECT_TO_CONNECT_WALLET:"CONNECT_TO_CONNECT_WALLET",
     DISCONNECT_METAMASK: "DISCONNECT_METAMASK",
     DISCONNECT_WALLET : "DISCONNECT_WALLET",
     GET_SOCIALFI: "GET_SOCIALFI",
     GET_LIST_MARKET: " GET_LIST_MARKET"
})

export default actionTypes;
